### ISSUE TITLE
Check ZED IMU and magnetometer

### ISSUE THREAD

**Issue by toyat522** [ArcturusNavigation/all_seaing_vehicle#100]
Visualize them on RViz, how are they?

**Comment by sanjithudupa** [comment]
## startup
Run `ros2 launch zed_wrapper zed_camera.launch.py camera_model:='zed2i'`

## camera data
In rviz, the camera image topic is visible under `/zed/zed_node/rgb/image_rect_color`
- there is also a pose `/zed/zed_node/pose` that holds the pose of the zed calculated by the node

## imu data
imu topic: `/zed/zed_node/imu/data` -- not visualizable in ROS but is standard IMU message type
 - looks like the angle is absolute relative to the earth (not sure if we can zero it ?) 
mag topic: `/zed/zed_node/imu/mag` -- has the magnetometer data in 3 axes
